### ISSUE TITLE
./migrate-database.sh: line 6: cake: command not found

### ISSUE THREAD

**Issue by cw-aleks** [openshift/cakephp-ex#41]
Hi.

we used today this example with errors.

```
oc logs -f cakephp-mysql-example-1-prehook
```
```
Generating database schema 'cake schema generate' ...
./migrate-database.sh: line 6: cake: command not found
```

The build was successfully

```
oc get po
NAME                              READY     STATUS      RESTARTS   AGE
cakephp-mysql-example-1-build     0/1       Completed   0          14m
cakephp-mysql-example-1-deploy    0/1       Error       0          13m
cakephp-mysql-example-1-prehook   0/1       Error       0          13m
```

**Comment by bparees** [comment]
Can you give me recreate steps?  you just instantiated the template https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql.json ?

can you also provide me with the output of "oc get dc -o yaml"?

**Comment by cw-aleks** [comment]
The customer just select this example from the openshift template page.

oc get dc  -o yaml cakephp-mysql-example

https://gist.github.com/cw-aleks/2c4fdad75bbc1aff2452f35fb9126bb3

oc version
oc v3.1.1.6
kubernetes v1.1.0-origin-1107-g4c8e6f4

**Comment by bparees** [comment]
@cw-aleks is the customer using the rhel imagestreams or the centos imagestream?  can you share "oc get is -n openshift -o yaml" ?

**Comment by cw-aleks** [comment]
To me it looks like rhel

https://gist.github.com/cw-aleks/ae5b6f35b151e27164b6ac9ee21ec863

**Comment by bparees** [comment]
those image streams appear very out of date, for comparison here's what they look like for me.. note the dates of yours are from february:

```
status:
  dockerImageRepository: 172.30.226.61:5000/openshift/php
  tags:
  - items:
    - created: 2016-08-22T19:39:39Z
      dockerImageReference: registry.access.redhat.com/rhscl/php-56-rhel7:latest
      generation: 2
      image: 5b30d4ad5edf47220b432088a53fb00d35f744b81c728eb47c57d86d2e0da6ed
    tag: latest
  - items:
    - created: 2016-08-22T19:39:39Z
      dockerImageReference: registry.access.redhat.com/rhscl/php-56-rhel7:latest
      generation: 2
      image: 5b30d4ad5edf47220b432088a53fb00d35f744b81c728eb47c57d86d2e0da6ed
    tag: "5.6"
  - items:
    - created: 2016-08-22T19:39:39Z
      dockerImageReference: registry.access.redhat.com/openshift3/php-55-rhel7:latest
      generation: 2
      image: 57bf552850346d46370b4f70ea4075bec956a8c9466dd42889e711d6ccaaf967
    tag: "5.5"
```

can you run "oc import-image php -n openshift" to update your cluster's php imagestreams?
